### ISSUE TITLE
Allow color to be undefined

### ISSUE THREAD

**Issue by wooden-worm** [lennartkloock/dioxus-material-icons#8]
Currently the library always set `color`: ```color: {cx.props.color.to_css_color()}```

Please consider making `color` an optional property. This allows the color to be inherited from the parent node.

**Comment by lennartkloock** [comment]
Does this solve your issue?

When merged, you can write:
```rs
MaterialIcon { name: "home" }
```
The icon will then don't have the css property `color`

**Comment by lennartkloock** [comment]
And thanks for your feedback. It's a pretty good idea to inherit the color by default. I think I will do it for the size prop too.

**Comment by wooden-worm** [comment]
The PR looks perfect, thank you!
